homepage:
  path: /
  defaults: { _controller: BlogBundle:Default:index }

dblist:
  path: /dblist
  defaults: { _controller: BlogBundle:Default:dblist}

new:
  path: /new
  defaults: { _controller: BlogBundle:Default:new}

dbview:
  path: /dbview/{uN}
  defaults: { _controller: BlogBundle:Default:dbview}

dbedit:
  path: /dbedit/{uN}
  defaults: { _controller: BlogBundle:Default:dbedit}

delete:
  path: /delete/{uN}
  defaults: { _controller: BlogBundle:Default:delete}