homepage:
  path: /
  defaults: { _controller: BlogBundle:Default:index }

list:
  path: /list
  defaults: { _controller: BlogBundle:Default:list}

dblist:
  path: /dblist
  defaults: { _controller: BlogBundle:Default:dblist}

new:
  path: /new
  defaults: { _controller: BlogBundle:Default:new}

edit:
  path: /edit/{uN}
  defaults: { _controller: BlogBundle:Default:edit}
  requirements:
    uN: '\d+'

dbedit:
  path: /dbedit/{uN}
  defaults: { _controller: BlogBundle:Default:dbedit}
  requirements:
    uN: '\d+'

delete:
  path: /delete/{uN}
  defaults: { _controller: BlogBundle:Default:delete}